### ISSUE TITLE
High level peer review of the baseline solution

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/github-actions-ci-cd#30]
@emteknetnz has a refactored approach that should be merge back into the main repo.

We need to have a high level review to make sure the approach is fit for purpose.

# Acceptance Criteria
- [ ] We are satisfied that all the high level requirements below are achievable with the current approach.
- [ ] Other cards in the EPIC are not foreclosed with the current approach.
- [ ] A high level peer review of the current WIP solution is performed to identify major defects or shortcomings.
- [ ] Shortcomings or problems are identified in follow up cards.

# High level requirements
- Multi DB support
- Auto-detect pull request target and install matching dependencies
- Can run individual builds
- Figure out how to run custom builds
- Older release lines are still tested with EOL PHP version even once new releases lines and PHP versions are released
- This works for tags as well as branches

**Comment by ChloeSartorelli** [comment]
## Questions and observations so far

1. What is the intention of the 'simple' matrix that only tests PHP7.4?
1. https://github.com/emteknetnz/gha-generate-matrix/blob/320eae145e1c9543d3fe9d6f17ea283b09feb3ac/script.php#L55
    - `run_phplinting` is ignored
1. How do we dynamically say "if this is CMS4.9, use php versions x, y, z - if CMS4.x, use php version 7.4, 8.0, 8.1"? Currently it's hard-coded to 7.4 and 8.0 for everything (though 8.0 can be skipped for "simple" matrices).
    - These hard-coded values stretch beyond just the matrix builder as well - there's a condition in ci.yml (see note about graphql versions below) 
    - One option could be to have a separate array that says, for example. "installer 4.9 uses php 7.3, 7.4 - installer 4.10 uses php 7.4, 8.0 - installer 4.11 uses php 7.4, 8.0, 8.1". We can then just keep that updated as we introduce new PHP versions for new CMS major/minors, and both current and old versions will automatically grab the correct values.
    - Outside the context of a given matrix - we're running some steps on explicitly PHP 7.4 (such as generating the matrix) - it might be better to instead have an input for "run steps on this PHP version if not in the context of a given matrix" where we can just update that value in a single place for everything that needs it - that was as PHP versions go EOL we can very easily avoid using them
1. https://github.com/emteknetnz/gha-generate-matrix/blob/320eae145e1c9543d3fe9d6f17ea283b09feb3ac/script.php#L62-L67
    - Why does `'php' => '7.4'` denote graphql v3, and php8.0 denote v4? When php 7.4 goes EOL how will we say "test graphql v3 in this build"?
    - This is _sort of_ [handled in ci.yml](https://github.com/emteknetnz/github-actions-ci-cd/blob/0e8dcd990df0209dd1c62f741ed84fb69618a814/.github/workflows/ci.yml#L272-L276) - I do think having this separate from the php version would be better. Otherwise every time we update php versions we also have to update this condition in both places, which could be easily forgotten in the future. Maybe matrix generation should have something like `if ($run['endtoend']) { $matrix['graphql'] = [3, 4]; }` or "if even use graphql 3, if odd use graphql 4" (or some other way of saying "add 3 for some builds and 4 for others" that doesn't rely on specific php versions being checked outside of the construction of the matrix)
1. https://github.com/emteknetnz/gha-generate-matrix/blob/320eae145e1c9543d3fe9d6f17ea283b09feb3ac/script.php#L38-L52
    - What happens if there is a default _and_ other suites listed in the phpunit.xml file? Why do we explicitly _not_ use the default suite in that case?
1. https://github.com/emteknetnz/github-actions-ci-cd/blob/0e8dcd990df0209dd1c62f741ed84fb69618a814/.github/workflows/ci.yml#L121-L124
    - Probably matrix generation should include naming the test and artifacts (i.e. `env.artifacts_name: ${{matrix.artifacts_name}}` and `name: ${{matrix.name}}`
1. https://github.com/emteknetnz/github-actions-ci-cd/blob/0e8dcd990df0209dd1c62f741ed84fb69618a814/.github/workflows/ci.yml#L135
    - Currently hardcoded for composer2 but should be easy enough to make it do both (e.g. `if ($run['phpunit']) { $matrix['composer'] = [1, 2]; }` or just add composer 1 to one of the builds, and change that line to pull from the matrix)
1. https://github.com/emteknetnz/github-actions-ci-cd/blob/0e8dcd990df0209dd1c62f741ed84fb69618a814/.github/workflows/ci.yml#L244-L245
Both of these are referring to the target branch, i.e. branches in the `silverstripe` organisation (or dnadesign etc) on github - e.g. `4`, `4.10`, etc - so they won't have `pulls/`, I don't think?
1. https://github.com/emteknetnz/github-actions-ci-cd/blob/0e8dcd990df0209dd1c62f741ed84fb69618a814/.github/workflows/ci.yml#L260
    - For non-lock-stepped modules this will result in using the wrong (and in the worst case scenario, a non-existent) installer version. e.g. [silverstripe/config](https://github.com/silverstripe/silverstripe-config/) is currently only up to 1.4, so PR builds will be pulling in installer 4.4 (I notice that's in there as a hard-coded exception, but if there aren't other similar situations now there definitely will be in the future
    - This will be especially important when we start doing major releases again, which _could_ result in extracting bits of code into new core modules which may not be in lock-step - plus when we're supporting two major versions simultaneously how can we say "use 5.3.x for this, but 6.3.x for that"? Is there a way we can handle those dynamically?
    - This to me seems like the only major issue with the current setup (i.e. the only thing that might require significant effort and perhaps refactoring to achieve)
    - We may need to consider having this be a piece of metadata held in the repository (in a separate file or as a dev dependency or as extra config in composer.json or whatever) that gets updated (ideally by cow) when releases are done.
1. https://github.com/emteknetnz/github-actions-ci-cd/blob/0e8dcd990df0209dd1c62f741ed84fb69618a814/.github/workflows/ci.yml#L480-L485
    - Are artifacts kept and easily identified between runs? (e.g. `4.11` branch failsand then `4` branch passes - do we retain both sets of artifacts? Can we tell which is which?) How often does this get cleared out?
1. https://github.com/emteknetnz/gha-run-tests/blob/cbe584aca9c7d88a2797acc91557fda6040ddb32/action.yml#L39-L40
    - Will this exit if there's no end to end suite, but we only want to do phpunit tests? Or vice versa?
    - Also seems to disagree with the comments here: https://github.com/emteknetnz/gha-run-tests/blob/cbe584aca9c7d88a2797acc91557fda6040ddb32/action.yml#L7-L8
1. When running this in a fork of silverstripe-campaign-admin I saw:
    - > Cache hit occurred on the primary key shared-composer-cache, not saving cache.
    - Does this mean we share cache even for runs outside the silverstripe organisation? Is that safe?
1. Travis has a way to trigger a build on a branch at any time without having to push code - is there a way to do that with github actions?
1. The high level requirements say "This works for tags as well as branches" - I assume this is so that when we tag something we can see that the tag builds fine independently of the branch it is tagged from. I'm pegging that this will mostly be dependent on the dynamic (or not-necessarily-so-dynamic) detection of which version of installer to include in order to work. What else would we need for this to work correctly on tags?

**Comment by emteknetnz** [comment]
1. Runs faster, more for debugging ci.yml than anything else. I'm not too attached to it.
2. True, looks like there should be `&& $run['endtoend']` check in the conditional above
3. The gha-generate-matrix action is only ever going to be used in the context of running our CI, so we can do whatever we like in script.php.  We can add the repo name and pull-request target branch into `__inputs.yml`. Create a list of core lockstepped modules. If the repo is in the map, then workout the version of installer to use e.g. admin 1.9 uses installer 4.9. Also have a map of php versions corresponding to each version of installer. Add the version of installer to install as an output of script.php
4. I think it's best to handle all of this sort of logic within gha-generate-matrix.  We'll also add in other things here such as database (mysql 5.7, mysql 8.0, postgres, PDO).  We already do impure tests where we change multiple variables in a single job, such as changing the PHP version and the database, therefore isolating neither.  This is done to preserve resources.  See - https://github.com/silverstripe/silverstripe-travis-shared/blob/master/config/jobs/installer-range.yml#L17 - we're testing MySQL, Postgres + PDO in different jobs.  When PHP versions go EOL, we'll just update gha-generate-matrix
5. It'll ignore the default and only use the other suites.  I can't recall seeing a phpunit.xml where the test folders contains in the default suite weren't also covered by the other suites too.  If you find an example of where this isn't the case in a module, then we should update the modules phpunit.xml file
6. Yeah that seems fairly sensible, the bash logic is awful reading
7. Yep, another variable we can add to generate-matrix.  We'll also want a --prefer-lowest job, possible as the same job
8. Yeah seems like it.  Worst case scenario the regex replace on pulls/ does nothing, so no harm done
9. Yes currently broken.  We need a list of core lock-stepped modules here and check the repo is in there.  If the repo is not, then use installer 4.x-dev or 4.11.x-dev.  To get the latest 4.11.x-dev type of branch, we could either hardcode it here (error prone) or dynamically work it out from https://api.github.com/repos/silverstripe/silverstripe-installer/branches
10. Yes, they are unique per run.  I forget how long they are retained for, 30/60/90 days or something like that.  Same as logs (unfortunately, unlike travis they get removed after a while).  Example artifacts (scroll to bottom) https://github.com/emteknetnz/silverstripe-campaign-admin/actions/runs/2013214049
11. It won't exit if there's no tests.  What it does is exit if there are any non-alpha or non-number or other non-valid characters.  It's validating string inputs.
12. I'm not sure, needs further investigation. The intention is to make composer installation between runs a lot faster
13. Yes, I'm not sure if it's configured correctly right now, though it should be doable - https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/
14. I'm not sure, I can't rememeber if I gave any consideration to tags.  There's a tag trigger - https://stackoverflow.com/questions/61891328/trigger-github-action-only-on-new-tags

**Comment by ChloeSartorelli** [comment]
With 4. my point is that we shouldn't have to update the matrix when php versions change. We should only have to update the list from 3. (i.e. the mapping of installer versions to php versions) - which version of graphql is used should not be dependent on php versions.
But I accept that would be an easy change to make so no worries there.

With 11, don't those conditions say "If the input string doesn't match `^[a-zA-Z0-9_\-]*$` exit the run"? So if the input string is empty for `$ENDTOEND_SUITE`, it will exit. But if this is a module that simple _doesn't have_ any end to end tests, we shouldn't exit.
Unless I have misunderstood how the condition works, which is entirely possible.
In any case that's something that will be easy to fix if it needs to be fixed, so not a blocker.

For 12 I think I was just looking at a not-the-first job within the first run - which would be expected to be a cache hit because it's getting cache from a prior job in that run. But it still warrants some investigation of just how this cache sharing works so we can be confident about how it works.

## SUMMARY
- Some investigation needs to be done on whether composer cache is being shared outside the silverstripe organisation and if so, whether there are security implications to that.
- There is a way forward for ensuring supported modules use the correct installer and php versions (requires updating a list each release - can be automatically updated via cow or similar)
    - Need to confirm if this will work with tags - but given tags are just semantic numbering I don't see why that would be any different to basing it off branch numbers.
- There are some things that aren't perfect in the current code, but that is expected at this stage as it's effectively a POC.
- There is nothing in the current approach that precludes the requirements or additional functionality/features that we have identified.
- There are some assumptions here that would make this less useful for third parties and even our own unsupported modules - if that is a concern we can just add a "installer constraint override" input and maybe "php versions override" input and document those. That would bypass the mapping discussed in questions 3 and 9 above.

**Comment by emteknetnz** [comment]
> One option could be to have a separate array that says, for example. "installer 4.9 uses php 7.3, 7.4 - installer 4.10 uses php 7.4, 8.0

That's aligned with my thinking.  We define all the things in generate-matrix script.php

> 11

`var_dump(preg_match('#^[a-zA-Z0-9_\-]*$#', '')); = int(1)` There's a `*` in there, so it matches empty strings

**Comment by maxime-rainville** [comment]
This looks good to me. Can you create cards for Guy's last comment ... or update the ACs on some existing card to cover those points?

If you're both satisfied that the ACs have been broadly met, we can close this card.

**Comment by emteknetnz** [comment]
I've created new issues

- https://github.com/silverstripe/github-actions-ci-cd/issues/31
- https://github.com/silverstripe/gha-ci/issues/12

I'll close this now
